@startuml
skinparam linetype ortho
skinparam dpi 200

package Application {
  class ChessRulesSubsystem {
    +4: To which squares may a rook move?
    +10: How many points is a rook worth in scoring?
    +21: Validate move legality
    +24: What are the rules of chess?
  }

  class CurrentGameValidatorSubsystem {
    +8: Is white checkmated?
    +11: Is white still allowed to castle?
    +15: Has black already castled?
    +25: Get list of all possible valid moves
  }

  class GameHistorySubsystem {
    +17: What did the board look like four moves ago?
    +19: What was black’s most recent move?
    +20: How many moves is the current match old?
  }

  class BoardStateSubsystem {
    +7: What is the score for white?
    +9: Whose turn is it?
    +14: Which chesspiece is occupying square b2?
  }

  class AISubsystem {
    +2: What is the optimal move in the following situation?
  }

  class GameLogicSubsystem {
    +22: Undo move
    +23: Offer draw
  }

  class ChessGameLoopSubsystem {
    +25: Present game to user
  }
  
  class ChessGraphicsSubsystem {
    +3: Draw a white pawn on c4
    +6: Draw the following chess position
    +12: What size is a queen displayed on screen?
    +18: Draw an empty board
  }
}

package Technical {
  class InputSubsystem {
    +1: On which screen position did the most recent mouse click take place?
    +16: Which is the screen position of the most recent drop event?
    +13: On which square did the most recent mouse click happen?
  }

  class GraphicsSubsystem {
    +5: Draw a black dot at position [898, 266]
  }

  class PersistenceSubsystem {
    +26: Persist a game
    +27: Retrieve a game
  }
}

AISubsystem --> BoardStateSubsystem
AISubsystem --> GameLogicSubsystem
BoardStateSubsystem --> GameLogicSubsystem
ChessGameLoopSubsystem --> ChessGraphicsSubsystem
ChessGameLoopSubsystem --> InputSubsystem
ChessGraphicsSubsystem --> BoardStateSubsystem
ChessGraphicsSubsystem --> GraphicsSubsystem
CurrentGameValidatorSubsystem --> ChessRulesSubsystem
CurrentGameValidatorSubsystem --> GameHistorySubsystem
GameHistorySubsystem --> PersistenceSubsystem
GameLogicSubsystem --> CurrentGameValidatorSubsystem
GameLogicSubsystem --> GameHistorySubsystem
@enduml
